name: Well architected aks on Azure
on: workflow_dispatch

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Cli test
        uses: azure/CLI@v1
        with:
          azcli-version: 2.0.72
          inlineScript: |
            az account show 
            az storage -h
