name: Well architected aks on Azure - Destroy Terraform
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      # login to azure with service principal
      - name: Log in with Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      # Test azure connection
      - name: Azure Cli test
        uses: azure/CLI@v1
        with:
          azcli-version: 2.0.72
          inlineScript: |
            az account show 
            az storage -h
      # Check the repo
      - name: Checkout
        uses: actions/checkout@v3

      # Install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terrraform plan
        working-directory: ./terraform
        run: terraform plan -destroy -out tfplan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="script_storage_account_name=${{ secrets.SCRIPT_STORAGE_ACCOUNT_NAME }}" -var="script_storage_account_key=${{ secrets.SCRIPT_STORAGE_ACCOUNT_KEY }}"

      - name: Terrraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approved
