name: Well architected aks on Azure
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      # login to azure with service principal
      - name: Log in with Azure CLI
        uses: azure/actions/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Test azure connection
      - name: Azure Cli test
        uses: azure/CLI@v1
        with:
          azcli-version: 2.0.72
          inlineScript: |
            az account show 
            az storage -h
      # Check the repo
      - name: Checkout
        uses: actions/checkout@v3

      # Install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Checks that all terraform configuration files adhere to a canonical format
      - name: Terraform fmt
        working-directory: ./terraform
        run: terraform fmt -check
